### ISSUE TITLE
Connection Timing Out Although Proxy is Already Set

### ISSUE THREAD

**Issue by njquek001** [oracle/centos2ol#175]
Facing the below prompt after running the script. 

0curl: (7) Failed connect to yum.oracle.com:443; Connection timed out
Could not download public-yum-ol7.repo from https://yum.oracle.com.

        Are you behind a proxy? If so, make sure the 'http_proxy' environment

        variable is set with your proxy address.
For assistance, please open an issue via GitHub: https://github.com/oracle/centos2ol/.

**Comment by njquek001** [comment]
Have added the addresses in /etc/environment instead of using export. 

Now facing the below issue. 

[root@xxxxxxxxxxxxxx tmp]# sudo bash centos2ol.sh
Checking for required packages...
Checking your distribution...
package epel-release is not installed
Checking for yum lock...
Checking for required python packages...
Finding your repository directory...
Learning which repositories are enabled...
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1071, in <lambda>
    repos = property(fget=lambda self: self._getRepos(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 694, in _getRepos
    self.getReposFromConfig()
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 567, in getReposFromConfig
    self.getReposFromConfigFile(repofn, repo_age=thisrepo_age)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 465, in getReposFromConfigFile
    raise Errors.ConfigError(exception2msg(e))
yum.Errors.ConfigError: File contains no section headers.
file: file:///etc/yum.repos.d/switch-to-oraclelinux.repo, line: 1
'<HTML><HEAD>\r\n'

**Comment by scoter-oracle** [comment]
Script has been revamped. Please re-test and re-open the issue if it still fails.
